=== fzappa/campelmag/c++/campelmag/dados.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:element name="projeto" type="projetoType"/>
  <xs:complexType name="angabcType">
    <xs:sequence>
      <xs:element type="xs:float" name="a"/>
      <xs:element type="xs:float" name="b"/>
      <xs:element type="xs:float" name="c"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="linhamedType">
    <xs:sequence>
      <xs:element type="xs:float" name="xmin"/>
      <xs:element type="xs:float" name="xmax"/>
      <xs:element type="xs:float" name="passo"/>
      <xs:element type="xs:float" name="hmed"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="pxfeixesType">
    <xs:sequence>
      <xs:element type="xs:float" name="e"/>
      <xs:element type="xs:float" name="c"/>
      <xs:element type="xs:float" name="d"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="casoType">
    <xs:sequence>
      <xs:element type="xs:float" name="tensao"/>
      <xs:element type="xs:float" name="pot"/>
      <xs:element type="angabcType" name="angabc"/>
      <xs:element type="linhamedType" name="linhamed"/>
      <xs:element type="xs:float" name="coefm"/>
      <xs:element type="xs:float" name="hmax"/>
      <xs:element type="xs:float" name="flecha"/>
      <xs:element type="xs:float" name="espacsubcond"/>
      <xs:element type="xs:float" name="diamcabo"/>
      <xs:element type="xs:byte" name="ncond"/>
      <xs:element type="pxfeixesType" name="pxfeixes"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="projetoType">
    <xs:sequence>
      <xs:element type="xs:string" name="nome"/>
      <xs:element type="xs:byte" name="grafico">
        <xs:annotation>
          <xs:documentation>
      1 - PS
      2 - SVG
      3 - JPG
      4 - PNG
      5 - PDF
      6 - EPSLaTex
    </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="casoType" name="caso"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== fzappa/campelmag/c++/campelmag/dados.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="dados.xsl"?>
<projeto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="dados.xsd">
    <nome>LT 765kV - CAMPO MAGNÃ‰TICO</nome>
    <!--
      1 - PS
      2 - SVG
      3 - JPG
      4 - PNG
      5 - PDF
      6 - EPSLaTex
    -->
    <grafico>4</grafico>
      <caso>
        <tensao>765e3</tensao>
        <pot>2.2e9</pot>
        <angabc>
            <a>120.0</a>
            <b>0.0</b>
            <c>-120.0</c>
        </angabc>
        <linhamed>
          <xmin>-80.0</xmin>
          <xmax>80.0</xmax>
          <passo>0.5</passo>
          <hmed>1.5</hmed>
        </linhamed>
        <coefm>0.87</coefm>
        <hmax>25.0</hmax>
        <flecha>8.63</flecha>
        <espacsubcond>0.457</espacsubcond>
        <diamcabo>0.02959</diamcabo>
        <ncond>4</ncond>
        <pxfeixes>
          <e>-14.34</e>
          <c>0.0</c>
          <d>14.34</d>
        </pxfeixes>
      </caso>
</projeto>
